spring.application.name=Progreso
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/helptata_progreso
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

ms.logs.url=http://localhost:8081

# Datos de prueba (data.sql se ejecuta al iniciar)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
